In [1]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5])
res = arr**2   # Vectorization i.e directly performing operation on complete array at once

In [8]:
res

array([ 1,  4,  9, 16, 25])

In [9]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2,3])

result = arr1 + arr2 # Broadcasting arr2 across arr1
print(result)

[[2 4 6]
 [5 7 9]]
