In [1]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [5]:
# Flatten the array
flat = arr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
flat[1]

np.int64(2)

In [7]:
flat[0:3]

array([1, 2, 3])

In [8]:
flat[:-4]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
flat[-4:-2]

array([ 9, 10])

In [10]:
# Slicing returns a view not a copy

b = flat[3:7]
b

array([4, 5, 6, 7])

In [11]:
b[0] = 333333
b

array([333333,      5,      6,      7])

In [12]:
flat

array([     1,      2,      3, 333333,      5,      6,      7,      8,
            9,     10,     11,     12])

In [13]:
# If don't wish to change original array then, since it's not slicing then use copy()
b = flat[3:7].copy()

In [14]:
# Fancy indexing

arr = np.array([10,20,30,40,50])
ind = [0,2,4] # indices to print
arr[ind]

array([10, 30, 50])

In [15]:
# Boolean masking
mask = arr>25
arr[mask]

array([30, 40, 50])