In [1]:
import numpy as np

In [3]:
# Axis 0 -> rows
# Axis 1 -> columns

arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# summing along axis
np.sum(arr,axis=0)

array([12, 15, 18])

In [5]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [7]:
# Indexing in multidimesnional arrays using numpy

# [row , col]

arr[0:2, 1:3 ] # 0-1 rows and 1-3 cols

array([[2, 3],
       [5, 6]])

In [8]:
# array of 2D arrays

arr2 = np.array([

    [[1,2,3],
     [4,5,6]],
    
  [[7,8,9],
   [10,11,12]]
    
])

In [13]:
arr2[:,0,:] #3D array (depth,row,col) means (: means consider all 2D arrays, 0 means first array in both 2D arrays, :) means all columns

array([[1, 2, 3],
       [7, 8, 9]])

In [14]:
arr2[:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [16]:
arr2[0,1,:] # 0 means consider first 2D array only then inside that 1st array and all cols

array([4, 5, 6])

In [17]:
arr2[0,1,:]=0
arr2

array([[[ 1,  2,  3],
        [ 0,  0,  0]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
# Indexing works as arr(row,col) for 2D arrays and (depth,row,col) for 3D arrays