In [1]:
import numpy as np

In [3]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [10]:
arr=np.array([1,2,3,4])   # 1D array

In [11]:
arr

array([1, 2, 3, 4])

In [12]:
arr2 = np.array([[1,2,3],[4,5,6]]) # 2D array

In [13]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# Array of zeroes - we can direct use function instead of reating list and then converting to array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# Array of ones - we can direct use function instead of reating list and then converting to array

np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# Array of 2x2 filled with 7

np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [19]:
# Identity matrix
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
# Gives range and add the respective last no. to get the no.s between range
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [27]:
# Evenly spaced -> gives 5 no.s between 0 and 1 so that array size is 5
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
arr3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [30]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
arr3.shape

(4, 4)

In [33]:
arr3.size

16

In [35]:
# Dimensions - 2 means 2D array
arr3.ndim

2

In [37]:
# Data type
arr3.dtype

dtype('int64')

In [45]:
# To get arr3 type as float (we can specify particular data type)
arr3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],dtype='float32')

In [39]:
arr3

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]], dtype=float32)

In [40]:
arr3.dtype

dtype('float32')

In [42]:
# convert data type back to int
n = arr3.astype('int32')
n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int32)

In [47]:
# To reshape 
re=arr2.reshape((3,2))
re

array([[1, 2],
       [3, 4],
       [5, 6]])